#!/usr/bin/env python3
"""Serve the dashboard against SYNTHETIC data, for documentation screenshots.

    python3 tools/demo_dashboard.py            # then open http://127.0.0.1:8663/

Every name, address and path this produces is invented. That is the point: the
screenshots in README.md show a real dashboard rendering fabricated data, so they can
be regenerated by anyone without publishing what is on their own storage.

It stands up three things:

* a fake collector, serving the /stats and /sessions the dashboard reads;
* a synthetic observer.db, events.db and state.json, plus a sparse file tree that
  makes the fast-tier pools report realistic sizes while occupying no disk;
* a small front end that supplies a healthy /api/health -- the real health source
  checks systemd units and store freshness, which have nothing true to say on a
  documentation machine.

The data is arranged so that each verdict the page can render actually appears:
a promotion that was read afterwards, one that was not, and one whose file was never
read while a DIFFERENT file was being read at the time -- the shape of a promotion
that resolved to the wrong file.
"""
import json
import os
import pathlib
import sqlite3
import subprocess
import sys
import threading
import time
import urllib.request
from http.server import BaseHTTPRequestHandler, ThreadingHTTPServer

HERE = pathlib.Path(__file__).resolve().parent.parent
sys.path.insert(0, str(HERE))
import pamts_events                                              # noqa: E402

ROOT = pathlib.Path(os.environ.get("PAMTS_DEMO_ROOT", "/tmp/pamts-demo"))
OBS_PORT, WEB_PORT, FRONT_PORT = 8661, 8662, 8663
NOW = time.time()
G, M = 1024 ** 3, 1024 ** 2

PLEX, LMS, FILES = "10.0.0.20", "10.0.0.11", "10.0.0.31"
TV, FILM, MUS = "/media/library/tv", "/media/library/movies", "/media/library/music"
SERVICES = [{"client": PLEX, "uid": 101000, "name": "plex"},
            {"client": LMS, "uid": 114, "name": "lms"},
            {"client": LMS, "uid": 1000, "name": "navidrome"},
            {"client": LMS, "uid": 0, "name": "audiomuse"},
            {"client": FILES, "uid": 0, "name": "files"}]


def sparse_tree(base):
    """A library with realistic file SIZES and no disk cost.

    The tier scan measures st_size, so a sparse file reports its full length while
    occupying nothing -- which is what lets a 350G library live in a tmpdir.
    """
    import random
    random.seed(11)
    def mk(path, n):
        os.makedirs(os.path.dirname(path), exist_ok=True)
        with open(path, "wb") as f:
            f.truncate(n)
    for s in ("Documentary Series", "Comedy Series", "Drama Series", "Nature Series"):
        for ep in range(1, 9):
            mk(os.path.join(base, "tv", s, "S0%dE%02d.mkv" % (1 + ep % 3, ep)),
               int((6.4 + random.random() * 2.2) * G))
    for f in ("Film (2016)", "Another Film (2019)", "Third Film (2021)",
              "Fourth Film (2012)", "Fifth Film (2018)", "Sixth Film (2004)",
              "Seventh Film (2023)", "Eighth Film (1998)", "Ninth Film (2010)",
              "Tenth Film (2015)"):
        mk(os.path.join(base, "movies", f, f + " WEBDL-1080p.mkv"),
           int((7.1 + random.random() * 3.0) * G))
    for a in ("Artist One", "Artist Two", "Artist Three", "Artist Four", "Artist Five"):
        for al in range(1, 9):
            for tr in range(1, 13):
                mk(os.path.join(base, "music", a, "Album %d" % al, "%02d Track.flac" % tr),
                   int((38 + random.random() * 26) * M))


def build(root):
    root.mkdir(parents=True, exist_ok=True)
    sparse_tree(str(root / "media" / "fast"))

    # ---- observer.db ------------------------------------------------------
    import random
    random.seed(7)
    db = root / "observer.db"
    db.unlink(missing_ok=True)
    c = sqlite3.connect(db)
    c.executescript("""
    CREATE TABLE plays (path TEXT PRIMARY KEY, last_play REAL NOT NULL,
      play_count INTEGER NOT NULL DEFAULT 0, last_label TEXT, last_bytes INTEGER,
      updated REAL NOT NULL);
    CREATE TABLE sessions (ts REAL NOT NULL, path TEXT, dev INTEGER, ino INTEGER,
      client TEXT, label TEXT NOT NULL, bytes INTEGER, coverage REAL, duration REAL,
      rate REAL, requests INTEGER, monotonic REAL, method TEXT, tier TEXT,
      uid INTEGER, tier0 TEXT);
    CREATE INDEX sessions_ts ON sessions(ts);
    """)
    S = []
    def sess(ago, path, client, uid, label, mb, tier, tier0=None, cov=0.9, dur=600):
        S.append((NOW - ago, path, 110, random.getrandbits(50), client, label,
                  int(mb * M), cov, dur, mb * M / max(dur, 1), int(dur * 4), 0.99,
                  "splice", tier, uid, tier0 or tier))
    film = f"{FILM}/Film (2016)/Film (2016) WEBDL-1080p.mkv"
    # promoted while it was still being read: starts cold, ends hot
    sess(1500, film, PLEX, 101000, "PLAY", 1002.4, "hot", "cold", 0.18, 908)
    # the read that was happening while the WRONG file was promoted
    sess(5460, film, PLEX, 101000, "PLAY", 182.3, "cold", None, 0.03, 58)
    sess(300, f"{TV}/Documentary Series/S02E04.mkv", PLEX, 101000, "PLAY", 622.0, "hot", None, 0.31, 740)
    sess(900, f"{TV}/Comedy Series/S01E09.mkv", PLEX, 101000, "PLAY", 180.5, "cold", None, 0.09, 210)
    sess(4200, f"{TV}/Drama Series/S04E02.mkv", PLEX, 101000, "PLAY", 1700.0, "hot", None, 0.74, 1500)
    for i, t in enumerate(("01 Opening", "02 Second", "03 Third")):
        sess(600 + i * 180, f"{MUS}/Artist One/First Album/{t}.flac", LMS, 114, "PLAY", 32.0 + i, "hot", None, 1.0, 240)
    for i, t in enumerate(("01 Alpha", "02 Beta")):
        sess(2600 + i * 200, f"{MUS}/Artist Two/Second Album/{t}.flac", LMS, 1000, "PLAY", 41.0 + i, "cold", None, 1.0, 260)
    sess(1200, f"{FILM}/Film (2016)/cover.jpg", PLEX, 101000, "FETCH", 1.9, "cold", None, 1.0, 1)
    for i in range(40):
        sess(5000 + i * 90, f"{MUS}/Artist One/First Album/0{i % 3 + 1} Track.flac", FILES, 0, "COPY", 38.0, "cold", None, 1.0, 3)
    for i in range(14):
        sess(9000 + i * 120, f"{MUS}/Artist One/First Album/0{i % 3 + 1} Track.flac", LMS, 0, "PROBE", 0.02, "hot", None, 0.01, 0)
    for i in range(9):
        sess(11000 + i * 300, f"{TV}/Drama Series/S04E{i + 3:02d}.mkv", FILES, 0, "BULK", 2100.0, "cold", None, 1.0, 900)
    c.executemany("INSERT INTO sessions VALUES(%s)" % ",".join("?" * 16), S)
    last = {}
    for r in S:
        if r[5] in ("PLAY", "FETCH"):
            last[r[1]] = max(last.get(r[1], 0), r[0])
    c.executemany("INSERT OR REPLACE INTO plays VALUES(?,?,?,?,?,?)",
                  [(p, t, 2, "PLAY", 10 ** 8, t) for p, t in last.items()])
    c.commit(); c.close()

    # ---- events.db --------------------------------------------------------
    db = root / "events.db"
    db.unlink(missing_ok=True)
    c = sqlite3.connect(db)
    c.executescript(pamts_events.SCHEMA)
    T = []
    def tr(ago, kind, item, gb, label, reason, pool="__shared__"):
        b = int(gb * G); s = max(b / 2.05e8, 0.4)
        T.append((NOW - ago, kind, pool, None, item, b, s, b / s, label, reason))
    # read afterwards -> the promotion earned its place
    tr(5400, "promote", "Film (2016)/Film (2016) WEBDL-1080p.mkv", 5.47, "Film (2016)", "playing now")
    # never read, and a different file was being read at the time -> wrong file
    tr(5500, "promote", "Transcode-Output/Film (2016) WEBDL-1080p.m4v", 3.49,
       "Film (2016) [transcode]", "playing now")
    # lookahead that did not pay off: an expected cost, stated quietly
    tr(4200, "promote", "Documentary Series/S02E05.mkv", 2.30, "Documentary Series S02E05", "next-up")
    tr(4260, "promote", "Documentary Series/S02E06.mkv", 2.21, "Documentary Series S02E06", "lookahead")
    tr(4320, "promote", "Comedy Series/S01E10.mkv", 1.44, "Comedy Series S01E10", "lookahead")
    for i, t in enumerate(("01 Opening", "02 Second", "03 Third")):
        tr(3700 + i * 60, "promote", f"Artist One/First Album/{t}.flac", 0.031,
           f"First Album - {t}", "playing now", pool="music")
    for i in range(6):
        tr(20000 + i * 800, "evict", f"Drama Series/S03E{i + 1:02d}.mkv", 2.1,
           f"Drama Series S03E{i + 1:02d}", "stale 94d")
    for i in range(4):
        tr(40000 + i * 900, "evict", f"Artist Two/Second Album/0{i % 2 + 1} Track.flac",
           0.04, "Second Album", "stale 120d", pool="music")
    c.executemany("INSERT INTO transfers(ts,kind,pool,job,item,bytes,seconds,rate,"
                  "label,reason) VALUES(?,?,?,?,?,?,?,?,?,?)", T)
    SA = []
    for i in range(7 * 24):
        ts = NOW - i * 3600
        SA.append((ts, "__shared__", int((318 + (i % 30) * 0.45) * G), int(400 * G), None))
        SA.append((ts, "music", int((23.1 + (i % 18) * 0.07) * G), int(32 * G), None))
    c.executemany("INSERT INTO samples(ts,pool,footprint,budget,reserve) "
                  "VALUES(?,?,?,?,?)", SA)
    c.commit(); c.close()

    # ---- state.json -------------------------------------------------------
    (root / "state.json").write_text(json.dumps({
        "rate_bps": 2.07e8,
        "observed": {f"o{i}": 1 for i in range(185)},
        "promotions": {
            f"{TV}/Documentary Series": {"at": NOW - 4200, "label": "Documentary Series S02E05", "last_rel": "S02E05.mkv"},
            f"{FILM}/Film (2016)": {"at": NOW - 5400, "label": "Film (2016)", "last_rel": "Film (2016) WEBDL-1080p.mkv"},
            f"{TV}/Comedy Series": {"at": NOW - 4320, "label": "Comedy Series S01E10", "last_rel": "S01E10.mkv"},
            f"{MUS}/Artist One/First Album": {"at": NOW - 3700, "label": "First Album", "last_rel": "01 Opening.flac"},
        }}, indent=1))

    # ---- config -----------------------------------------------------------
    fast = root / "media" / "fast"
    slow = root / "media" / "slow"
    (root / "pamts.toml").write_text(f"""
[[players]]
name = "plex"
kind = "plex"

[[players]]
name = "lms"
kind = "lms"

[[players]]
name = "storage"
kind = "storage"

[[roots]]
player_path = "{TV}"
fast = "/media/fast/tv"
slow = "/media/slow/tv"

[[roots]]
player_path = "{FILM}"
fast = "/media/fast/movies"
slow = "/media/slow/movies"

[[roots]]
player_path = "{MUS}"
fast = "/media/fast/music"
slow = "/media/slow/music"

[tier]
budget_gb = 400
settle_seconds = 900
new_grace_days = 14
promote_protect_days = 7
next_up_max_items = 24
next_up_max_gb = 60
dest_fstypes = ["nfs", "nfs4"]

[promote]
headroom_gb = 60
min_free_gb = 100
headroom_fraction = 0.30
max_items = 24
max_bytes_gb = 60
poll_seconds = 60
default_rate_mbps = 80

[[promote.rules]]
match = "movie"
current = {{ after_seconds = 120 }}
lookahead = {{ items = 0 }}
max_bytes_gb = 40

[[promote.rules]]
match = "episode"
current = {{ after_seconds = 300 }}
lookahead = {{ items = 3 }}
max_bytes_gb = 24

[[promote.rules]]
match = "track"
current = {{ after_seconds = 30 }}
lookahead = {{ items = 20 }}
max_bytes_gb = 3

[[jobs]]
name = "tv"
mode = "tier"
source = "{fast}/tv/"
dest = "{slow}/tv/"
depth = 1

[[jobs]]
name = "movies"
mode = "tier"
source = "{fast}/movies/"
dest = "{slow}/movies/"
depth = 1

[[jobs]]
name = "music"
mode = "tier"
source = "{fast}/music/"
dest = "{slow}/music/"
depth = 2
budget_gb = 32

[[jobs]]
name = "documents"
mode = "backup"
source = "/media/documents/"
dest = "/media/documents-backup/"
max_delete = 50
""".lstrip())


# --------------------------------------------------------------------- servers
LIVE = [
    {"path": f"{TV}/Documentary Series/S02E04.mkv", "label": "PLAY", "client": PLEX,
     "uid": 101000, "uids": [101000], "service": "plex", "bytes": 652214272,
     "coverage": 0.31, "started": NOW - 740, "idle_s": 0.4, "tier": "hot", "tier0": "hot"},
    {"path": f"{FILM}/Film (2016)/Film (2016) WEBDL-1080p.mkv", "label": "PLAY",
     "client": PLEX, "uid": 101000, "uids": [101000], "service": "plex",
     "bytes": 1051071216, "coverage": 0.18, "started": NOW - 908, "idle_s": 0.2,
     "tier": "hot", "tier0": "cold"},
    {"path": f"{MUS}/Artist One/First Album/02 Second.flac", "label": "PLAY",
     "client": LMS, "uid": 114, "uids": [114], "service": "lms", "bytes": 34603008,
     "coverage": 1.0, "started": NOW - 240, "idle_s": 1.1, "tier": "hot", "tier0": "hot"},
    {"path": f"{MUS}/Artist Two/Second Album/01 Alpha.flac", "label": "COPY",
     "client": FILES, "uid": 0, "uids": [0], "service": "files", "bytes": 39845888,
     "coverage": 1.0, "started": NOW - 30, "idle_s": 0.0, "tier": "cold", "tier0": "cold"},
]
STATS = {"kernel_emitted": 290800, "records": 290800, "kernel_dropped": 0,
         "sessions_open": len(LIVE), "sessions_closed": 297, "index_files": 255459,
         "arrivals": 4, "bulk_suppressed": 2, "folded_requests": 0,
         "userspace_pending": 0, "userspace_dropped": 0, "uptime_s": 486000,
         "service_map": SERVICES, "tiers": {"hot": 181243, "cold": 74216, "unknown": 0}}
CHECKS = [
    ("PAMTS", "pamts-observer", "active, 5d 15h"), ("PAMTS", "pamts-web", "active, 5d 15h"),
    ("PAMTS", "pamts-promote", "last run 0m ago, rc=0"),
    ("PAMTS", "pamts-nightly", "last run 17h ago, rc=0"),
    ("PAMTS", "nightly timer", "next in 7h 12m"),
    ("Collector", "eBPF tap", "9 probes attached"), ("Collector", "kernel drops", "0"),
    ("Collector", "ingest queue", "0 pending, 0 dropped"),
    ("Collector", "inode index", "255,459 files"),
    ("Stores", "observer.db", "updated 0m ago"), ("Stores", "events.db", "updated 10m ago"),
    ("Stores", "state.json", "updated 10m ago"),
    ("Capacity", "movies + tv (shared)", "326.7G of 400.0G"),
    ("Capacity", "music", "24.1G of 32.0G"), ("Capacity", "filesystem free", "4.6T"),
    ("Sources", "plex", "reachable, 2 playing"), ("Sources", "lms", "reachable, 1 playing"),
    ("Sources", "storage", "observer reachable"),
]


def serve(port, handler):
    t = threading.Thread(target=ThreadingHTTPServer(("127.0.0.1", port), handler)
                         .serve_forever, daemon=True)
    t.start()


def json_handler(route):
    class H(BaseHTTPRequestHandler):
        def do_GET(self):
            body = json.dumps(route(self.path)).encode()
            self.send_response(200)
            self.send_header("Content-Type", "application/json")
            self.send_header("Content-Length", str(len(body)))
            self.end_headers(); self.wfile.write(body)
        def log_message(self, *a): pass
    return H


def front_handler():
    class H(BaseHTTPRequestHandler):
        def do_GET(self):
            if self.path.startswith("/api/health"):
                body = json.dumps({
                    "overall": "ok", "generated": time.time(),
                    "counts": {"ok": len(CHECKS), "warn": 0, "fail": 0},
                    "checks": [{"group": g, "name": n, "state": "ok", "detail": d}
                               for g, n, d in CHECKS]}).encode()
                ctype, status = "application/json", 200
            else:
                try:
                    with urllib.request.urlopen(
                            f"http://127.0.0.1:{WEB_PORT}{self.path}", timeout=10) as r:
                        body = r.read()
                        ctype = r.headers.get("Content-Type", "text/html")
                        status = r.status
                except Exception as e:                           # noqa: BLE001
                    body, ctype, status = str(e).encode(), "text/plain", 502
            self.send_response(status)
            self.send_header("Content-Type", ctype)
            self.send_header("Content-Length", str(len(body)))
            self.end_headers(); self.wfile.write(body)
        def log_message(self, *a): pass
    return H


def main():
    print(f"building synthetic data under {ROOT} ...", file=sys.stderr)
    build(ROOT)
    serve(OBS_PORT, json_handler(
        lambda p: {"sessions": LIVE} if p.startswith("/sessions")
        else STATS if p.startswith("/stats") else {"ok": True}))
    web = subprocess.Popen([sys.executable, str(HERE / "pamts-web.py"),
                            "--config", str(ROOT / "pamts.toml"),
                            "--observer-url", f"http://127.0.0.1:{OBS_PORT}",
                            "--observer-db", str(ROOT / "observer.db"),
                            "--state-file", str(ROOT / "state.json"),
                            "--events-db", str(ROOT / "events.db"),
                            "--listen", f"127.0.0.1:{WEB_PORT}",
                            "--sources", "observer,state,config,events,history,tier"],
                           stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL)
    time.sleep(3)
    serve(FRONT_PORT, front_handler())
    print(f"demo dashboard on http://127.0.0.1:{FRONT_PORT}/  (ctrl-c to stop)",
          file=sys.stderr)
    try:
        while True:
            time.sleep(3600)
    except KeyboardInterrupt:
        pass
    finally:
        web.terminate()
    return 0


if __name__ == "__main__":
    sys.exit(main())
